serve:
  secret: MySecret
  port: 3000


events:
  github:
      comment: 
        - contains: /needs-performance-tests
          destination: jenkins
          values:
            target: test

        - condition:  ${{.Input.Payload.Branch eq "test" }}
          destination: jenkins
          values:
            target: preview

  cli:
      stdin:
        - contains: test
          destination: Test
          values:
            test: great


destinations:
  http:
      get:
        - name: Jenkins
          url:  http://admin:114845acdfac8737510c54607e2af78a84@localhost:8080/job/{{.Values.target}}/build

        - name: Demo
          url:  http://localhost:{{ .Values.Serve.port }}/webhook/generic?
  debug:
      stdout:
        - name: Test
          text: This is a {{ .Values.test}} message






#curl -f -k -H 'Content-Type: application/json' -XPOST --user login:secret https://ansible.dzbank.vrnet:443/api/v2/job_templates/197/launch/

#name: set gitlab merge url set_fact: gitlab_merge_url: "https://git.dzbank.vrnet/api/v4/projects/{{ tower_webhook_status_api.split("/")[6] }}/merge_requests/{{ tower_webhook_payload.object_attributes.iid }}/notes"

#name: set microservice url set_fact: microservice_url: "https://dfvvp01ciops.dzbank.vrnet/artifactory/helm-unstable-local/harissa/{{ tower_webhook_payload.object_attributes.source.path_with_namespace.split("/")[3] }}/{{ tower_webhook_payload.object_attributes.source.path_with_namespace.split("/")[3] }}-9.9.9-{{ tower_webhook_payload.object_attributes.last_commit.id }}-{{ tower_webhook_payload.object_attributes.source_branch.split("/")[1] }}-SNAPSHOT.tgz"
#name: set microservice version set_fact: microservice_version: "9.9.9-{{ tower_webhook_payload.object_attributes.last_commit.id }}-{{ tower_webhook_payload.object_attributes.source_branch.split("/")[1] }}-SNAPSHOT"
#name: set service name set_fact: microservice_name: "{{ tower_webhook_payload.object_attributes.source.path_with_namespace.split("/")[3] }}"
#name: set workspace set_fact: workspace: "{{ tower_webhook_payload.object_attributes.source_branch.split("/")[1] | lower}}" 08:50 Uhr
#name: curl gitlab merge request uri: url: "{{ gitlab_merge_url }}" method: POST status_code: 201 body: "body=Ansible Pipeline pending" headers: PRIVATE-TOKEN: "xxx"

